# Example configuration file for prometheus-openstack-exporter
# Copyright (C) 2016 Canonical, Ltd.
#

check_certs: false
listen_port: 9183
cache_refresh_interval: 300  # In seconds
cache_file: /var/cache/prometheus-openstack-exporter/mycloud
cloud: mycloud
poll_batch_size: 50

openstack_allocation_ratio_vcpu: 2.5
openstack_allocation_ratio_ram: 1.1
openstack_allocation_ratio_disk: 1.0

# To export hypervisor_schedulable_instances metric set desired instance size
schedulable_instance_size:
    ram_mbs: 4096
    vcpu: 2
    disk_gbs: 20

# There is no way to retrieve them using OpenStack APIs
# For clouds deployed without swift, remove this part
swift_hosts:
    - host1.example.com
    - host2.example.com

# Uncomment if the cloud doesn't provide cinder / nova volumes:
#use_nova_volumes: False

logging:
    version: 1
    disable_existing_loggers: False
    formatters:
        simple:
            format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout

        info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: simple
            filename: info.log
            maxBytes: 10485760 # 10MB
            backupCount: 20
            encoding: utf8

        error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: simple
            filename: errors.log
            maxBytes: 10485760 # 10MB
            backupCount: 20
            encoding: utf8

    loggers:
        __main__:
            level: ERROR
            handlers: [console]
            propagate: no

    root:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler]